-- MySQL Script generated by MySQL Workbench
-- Вс 31 окт 2021 12:36:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema symonenko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema symonenko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `symonenko` ;
USE `symonenko` ;

-- -----------------------------------------------------
-- Table `symonenko`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `country_name_idx1` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`city` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index3` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `symonenko`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`stantion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`stantion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Stantion_name_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_Stantion_City1`
    FOREIGN KEY (`city_id`)
    REFERENCES `symonenko`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`solar_panel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`solar_panel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `power` INT NULL,
  `capacity` VARCHAR(45) NULL,
  `Stantion_id` INT NOT NULL,
  `year of installation` YEAR(4) NULL,
  `garantee` INT NULL DEFAULT 25,
  PRIMARY KEY (`id`),
  INDEX `solar_panel_id_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_SolarPanel_Stantion`
    FOREIGN KEY (`Stantion_id`)
    REFERENCES `symonenko`.`stantion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`current_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`current_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `charge` FLOAT NULL,
  `angle` FLOAT NULL,
  `energy_do` INT NULL,
  `SolarPanel_id` INT NOT NULL,
  `date` DATE NULL DEFAULT curdate(),
  `time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SolarPanel_has_info_idx` (`SolarPanel_id` ASC) VISIBLE,
  CONSTRAINT `fk_CurrentInfo_SolarPanel1`
    FOREIGN KEY (`SolarPanel_id`)
    REFERENCES `symonenko`.`solar_panel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price_of_kv` FLOAT NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `Stantion_id` INT NOT NULL,
  `date` DATE NULL DEFAULT curdate(),
  `time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `sale` (`date` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Stantion1`
    FOREIGN KEY (`Stantion_id`)
    REFERENCES `symonenko`.`stantion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `owner_name_idx` (`surname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `symonenko`.`Owner_has_Stantion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `symonenko`.`Owner_has_Stantion` (
  `owner_id` INT NOT NULL,
  `Stantion_id` INT NOT NULL,
  PRIMARY KEY (`owner_id`, `Stantion_id`),
  CONSTRAINT `fk_Owner_has_Stantion_Owner1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `symonenko`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Owner_has_Stantion_Stantion1`
    FOREIGN KEY (`Stantion_id`)
    REFERENCES `symonenko`.`stantion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
